{% set version = "0.5.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-protviz
  version: {{ version|replace("-", "_") }}

source:
  fn: protViz_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/protViz_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/protViz/protViz_{{ version }}.tar.gz
  sha256: 5b2ec208289bf5d09db080a364e216fe9cadf20d46695e9a1f03531943fdf633

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: lattice, RUnit, xtable
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.12.8

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.8

test:
  commands:
    - $R -e "library('protViz')"           # [not win]
    - "\"%R%\" -e \"library('protViz')\""  # [win]

about:
  home: https://github.com/protViz/protViz/
  license: GPL-3
  summary: Helps with quality checks, visualizations  and analysis of mass spectrometry data,
    coming from proteomics  experiments. The package is developed, tested and used at
    the Functional  Genomics Center Zurich. We use this package mainly for prototyping,  teaching,
    and having fun with proteomics data. But it can also be  used to do data analysis
    for small scale data sets.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
