travis:
  secure:
    BINSTAR_TOKEN: 0KqTZYbiUHjHvuiZQIoQ20h7gUU8luckk2rnIhitMNL+TCED5dFnmywgri0AKdDl7oie6alSjrH2RfpPnVTJEVAK3pDrmbf5jYhlwksDvNC6CjyaB0b3w7xXTc5qKu5Ov0228t/Cd9yNZpKHPL93xYoAUtR90qyNIJQK/QbmeSv9BD5/wvw/a9yrHhmyoZyflXvalp3H9wdkFHVbwgwHeQABFUMVE2weYZzFa8y0OYXTeUAZOguUpwxC0wlbU6qiq5Bwf3hmXPvDJeARQ67UkEzXImHVya6jOM59TNfXQ93/ExHcGf/8aHnX0HkBFtMfHNeRIQnOhfh1pLboNg4TpxKTeaftQjjk6shaufdK0/k0vD6fKtQ0I1d1G4NDpQ12rybx6tPMzEdRQXdH69UaB6Ewjs7BxoDMU3ol5NFmt1tQG3pxVWrZQ/yTEv8fItQ+UI8YiV8RJ/bDZSdbFbnH1b51j73P1CzMx1XDG4oUWiNiyQ/K9mCLS/VtFn3MsM4GMR4Df8rHZm4P0cuTO60BPKNyCuVy9P7NjD1st9R4D65SRSL5Ovx8yfmFTl99rWt32V0159OsU14OkZHjAkqhPvO06rSe3PdVSdJkxElsd3kRJ8ckpymbSWVGSgAiLKEwmFpoqLljaHhaF/iU5KItjrQZCDrNqHN9ePDbfy+ucRU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
