travis:
  secure:
    BINSTAR_TOKEN: GTskZW391ojILeqGvcLId6xq4bh8f1eGhUybOJmz36dhOHllDCLRDtqWCoeyn8gWvmK991eOELCZ7C3P8NgoPBpc8qC3nba9v8QWBJP9/jHo8/5B8FhkhgD/7Tkf7nYRfPhewGWFbbKIcTK7S3LEk2oxnLtIyELbaZN5KWH5+pjIsF18EtQMmg4YgOOG6sdJgehaCpMb7Q4EKWP015h0gS4Q/gn9BDA3peWpDSGDnrUg6Wq2qkmXNetMgqPh5nyyP/0uyt3zZm/YMi8T6wnPdzaoeGSJhV/simnYCA0IT0aPgUHlcrHCcmeujC3AQ0FK1SWFTlMEkgbwbBWfd4VP1qubcRMBXk7tzt+nPNBKrEGQd5HluJ3mjd/VM6LX60kxtoDQbiHnxlsEBOLhPu6CvOaNNyprD8kJBuDK2ZeWAvDTQjJlpmvTpuKOAN+hF6BNn9SYn/GFixeOUykHWwRvA3sYe0G52wbq2eWVHFdQd4MbPKipG/iRos4mUpSfIFuWAWIgnIv+7EIcUeZteebaN/Z61CbRBtYMUQpKdVupwYK/uETg476+x0QNXLwHNthGRFPIpaesPaeZgtiyCht13TWxLQ6NAQep8H9z07YSuSIXojP4lWKlaoieXPdN+1qLBeiqAigNNCrH3X23hnR5g7Xmg60qbZ9LYZwqWlj7TLo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
